# Generated by Django 4.2.17 on 2024-12-18 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_artpiece'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artpiece',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='artpiece',
            name='description',
        ),
        migrations.RemoveField(
            model_name='artpiece',
            name='image',
        ),
        migrations.RemoveField(
            model_name='artpiece',
            name='year',
        ),
        migrations.AddField(
            model_name='artpiece',
            name='url',
            field=models.CharField(default='', max_length=255),
        ),
    ]
